mkdir /Users/charvieshukla/documents/AllSubjects/AIP
mkdir /Users/charvieshukla/documents/AllSubjects/AAS
mkdir /Users/charvieshukla/documents/AllSubjects/AWP
mkdir /Users/charvieshukla/documents/AllSubjects/ANES
mkdir /Users/charvieshukla/documents/AllSubjects/ANBI
mkdir /Users/charvieshukla/documents/AllSubjects/ANAR
mkdir /Users/charvieshukla/documents/AllSubjects/ANTH
mkdir /Users/charvieshukla/documents/AllSubjects/ANSC
mkdir /Users/charvieshukla/documents/AllSubjects/AESE
mkdir /Users/charvieshukla/documents/AllSubjects/AUD
mkdir /Users/charvieshukla/documents/AllSubjects/BENG
mkdir /Users/charvieshukla/documents/AllSubjects/BNFO
mkdir /Users/charvieshukla/documents/AllSubjects/BIEB
mkdir /Users/charvieshukla/documents/AllSubjects/BICD
mkdir /Users/charvieshukla/documents/AllSubjects/BIPN
mkdir /Users/charvieshukla/documents/AllSubjects/BIBC
mkdir /Users/charvieshukla/documents/AllSubjects/BGGN
mkdir /Users/charvieshukla/documents/AllSubjects/BGJC
mkdir /Users/charvieshukla/documents/AllSubjects/BGRD
mkdir /Users/charvieshukla/documents/AllSubjects/BGSE
mkdir /Users/charvieshukla/documents/AllSubjects/BILD
mkdir /Users/charvieshukla/documents/AllSubjects/BIMM
mkdir /Users/charvieshukla/documents/AllSubjects/BISP
mkdir /Users/charvieshukla/documents/AllSubjects/BIOM
mkdir /Users/charvieshukla/documents/AllSubjects/CMM
mkdir /Users/charvieshukla/documents/AllSubjects/CENG
mkdir /Users/charvieshukla/documents/AllSubjects/CHEM
mkdir /Users/charvieshukla/documents/AllSubjects/CHIN
mkdir /Users/charvieshukla/documents/AllSubjects/CCS
mkdir /Users/charvieshukla/documents/AllSubjects/CLIN
mkdir /Users/charvieshukla/documents/AllSubjects/CLRE
mkdir /Users/charvieshukla/documents/AllSubjects/COGS
mkdir /Users/charvieshukla/documents/AllSubjects/COMM
mkdir /Users/charvieshukla/documents/AllSubjects/COGR
mkdir /Users/charvieshukla/documents/AllSubjects/CSS
mkdir /Users/charvieshukla/documents/AllSubjects/CSE
mkdir /Users/charvieshukla/documents/AllSubjects/CGS
mkdir /Users/charvieshukla/documents/AllSubjects/CAT
mkdir /Users/charvieshukla/documents/AllSubjects/TDDM
mkdir /Users/charvieshukla/documents/AllSubjects/TDHD
mkdir /Users/charvieshukla/documents/AllSubjects/TDMV
mkdir /Users/charvieshukla/documents/AllSubjects/TDPF
mkdir /Users/charvieshukla/documents/AllSubjects/TDTR
mkdir /Users/charvieshukla/documents/AllSubjects/DSC
mkdir /Users/charvieshukla/documents/AllSubjects/DSE
mkdir /Users/charvieshukla/documents/AllSubjects/DERM
mkdir /Users/charvieshukla/documents/AllSubjects/DSGN
mkdir /Users/charvieshukla/documents/AllSubjects/DOC
mkdir /Users/charvieshukla/documents/AllSubjects/DDPM
mkdir /Users/charvieshukla/documents/AllSubjects/ECON
mkdir /Users/charvieshukla/documents/AllSubjects/EDS
mkdir /Users/charvieshukla/documents/AllSubjects/ERC
mkdir /Users/charvieshukla/documents/AllSubjects/ECE
mkdir /Users/charvieshukla/documents/AllSubjects/EMED
mkdir /Users/charvieshukla/documents/AllSubjects/ENG
mkdir /Users/charvieshukla/documents/AllSubjects/ENVR
mkdir /Users/charvieshukla/documents/AllSubjects/ESYS
mkdir /Users/charvieshukla/documents/AllSubjects/ETIM
mkdir /Users/charvieshukla/documents/AllSubjects/ETHN
mkdir /Users/charvieshukla/documents/AllSubjects/EXPR
mkdir /Users/charvieshukla/documents/AllSubjects/FMPH
mkdir /Users/charvieshukla/documents/AllSubjects/FPM
mkdir /Users/charvieshukla/documents/AllSubjects/FILM
mkdir /Users/charvieshukla/documents/AllSubjects/GPCO
mkdir /Users/charvieshukla/documents/AllSubjects/GPEC
mkdir /Users/charvieshukla/documents/AllSubjects/GPGN
mkdir /Users/charvieshukla/documents/AllSubjects/GPIM
mkdir /Users/charvieshukla/documents/AllSubjects/GPL
mkdir /Users/charvieshukla/documents/AllSubjects/GPPA
mkdir /Users/charvieshukla/documents/AllSubjects/GPPS
mkdir /Users/charvieshukla/documents/AllSubjects/GLBH
mkdir /Users/charvieshukla/documents/AllSubjects/GSS
mkdir /Users/charvieshukla/documents/AllSubjects/HITO
mkdir /Users/charvieshukla/documents/AllSubjects/HIEA
mkdir /Users/charvieshukla/documents/AllSubjects/HIEU
mkdir /Users/charvieshukla/documents/AllSubjects/HILA
mkdir /Users/charvieshukla/documents/AllSubjects/HISC
mkdir /Users/charvieshukla/documents/AllSubjects/HINE
mkdir /Users/charvieshukla/documents/AllSubjects/HIUS
mkdir /Users/charvieshukla/documents/AllSubjects/HIGL
mkdir /Users/charvieshukla/documents/AllSubjects/HIGR
mkdir /Users/charvieshukla/documents/AllSubjects/HILD
mkdir /Users/charvieshukla/documents/AllSubjects/HDS
mkdir /Users/charvieshukla/documents/AllSubjects/HUM
mkdir /Users/charvieshukla/documents/AllSubjects/INTL
mkdir /Users/charvieshukla/documents/AllSubjects/JAPN
mkdir /Users/charvieshukla/documents/AllSubjects/JWSP
mkdir /Users/charvieshukla/documents/AllSubjects/LATI
mkdir /Users/charvieshukla/documents/AllSubjects/LHCO
mkdir /Users/charvieshukla/documents/AllSubjects/LISL
mkdir /Users/charvieshukla/documents/AllSubjects/LIAB
mkdir /Users/charvieshukla/documents/AllSubjects/LIDS
mkdir /Users/charvieshukla/documents/AllSubjects/LIFR
mkdir /Users/charvieshukla/documents/AllSubjects/LIGN
mkdir /Users/charvieshukla/documents/AllSubjects/LIGM
mkdir /Users/charvieshukla/documents/AllSubjects/LIHL
mkdir /Users/charvieshukla/documents/AllSubjects/LIIT
mkdir /Users/charvieshukla/documents/AllSubjects/LIPO
mkdir /Users/charvieshukla/documents/AllSubjects/LISP
mkdir /Users/charvieshukla/documents/AllSubjects/LTAM
mkdir /Users/charvieshukla/documents/AllSubjects/LTCO
mkdir /Users/charvieshukla/documents/AllSubjects/LTCS
mkdir /Users/charvieshukla/documents/AllSubjects/LTFR
mkdir /Users/charvieshukla/documents/AllSubjects/LTGM
mkdir /Users/charvieshukla/documents/AllSubjects/LTGK
mkdir /Users/charvieshukla/documents/AllSubjects/LTIT
mkdir /Users/charvieshukla/documents/AllSubjects/LTKO
mkdir /Users/charvieshukla/documents/AllSubjects/LTLA
mkdir /Users/charvieshukla/documents/AllSubjects/LTRU
mkdir /Users/charvieshukla/documents/AllSubjects/LTSP
mkdir /Users/charvieshukla/documents/AllSubjects/LTTH
mkdir /Users/charvieshukla/documents/AllSubjects/LTWR
mkdir /Users/charvieshukla/documents/AllSubjects/LTEN
mkdir /Users/charvieshukla/documents/AllSubjects/LTWL
mkdir /Users/charvieshukla/documents/AllSubjects/LTEA
mkdir /Users/charvieshukla/documents/AllSubjects/MMW
mkdir /Users/charvieshukla/documents/AllSubjects/MBC
mkdir /Users/charvieshukla/documents/AllSubjects/MATS
mkdir /Users/charvieshukla/documents/AllSubjects/MATH
mkdir /Users/charvieshukla/documents/AllSubjects/MSED
mkdir /Users/charvieshukla/documents/AllSubjects/MAE
mkdir /Users/charvieshukla/documents/AllSubjects/MED
mkdir /Users/charvieshukla/documents/AllSubjects/MCWP
mkdir /Users/charvieshukla/documents/AllSubjects/MUS
mkdir /Users/charvieshukla/documents/AllSubjects/NANO
mkdir /Users/charvieshukla/documents/AllSubjects/NEU
mkdir /Users/charvieshukla/documents/AllSubjects/NEUG
mkdir /Users/charvieshukla/documents/AllSubjects/OPTH
mkdir /Users/charvieshukla/documents/AllSubjects/ORTH
mkdir /Users/charvieshukla/documents/AllSubjects/PATH
mkdir /Users/charvieshukla/documents/AllSubjects/PEDS
mkdir /Users/charvieshukla/documents/AllSubjects/PHAR
mkdir /Users/charvieshukla/documents/AllSubjects/SPPS
mkdir /Users/charvieshukla/documents/AllSubjects/PHIL
mkdir /Users/charvieshukla/documents/AllSubjects/PHYS
mkdir /Users/charvieshukla/documents/AllSubjects/PHYA
mkdir /Users/charvieshukla/documents/AllSubjects/POLI
mkdir /Users/charvieshukla/documents/AllSubjects/PSY
mkdir /Users/charvieshukla/documents/AllSubjects/PSYC
mkdir /Users/charvieshukla/documents/AllSubjects/RMAS
mkdir /Users/charvieshukla/documents/AllSubjects/RAD
mkdir /Users/charvieshukla/documents/AllSubjects/MGTF
mkdir /Users/charvieshukla/documents/AllSubjects/MGT
mkdir /Users/charvieshukla/documents/AllSubjects/MGTA
mkdir /Users/charvieshukla/documents/AllSubjects/MGTP
mkdir /Users/charvieshukla/documents/AllSubjects/RELI
mkdir /Users/charvieshukla/documents/AllSubjects/RMED
mkdir /Users/charvieshukla/documents/AllSubjects/REV
mkdir /Users/charvieshukla/documents/AllSubjects/SOMI
mkdir /Users/charvieshukla/documents/AllSubjects/SOMC
mkdir /Users/charvieshukla/documents/AllSubjects/SIOC
mkdir /Users/charvieshukla/documents/AllSubjects/SIOG
mkdir /Users/charvieshukla/documents/AllSubjects/SIOB
mkdir /Users/charvieshukla/documents/AllSubjects/SIO
mkdir /Users/charvieshukla/documents/AllSubjects/SXTH
mkdir /Users/charvieshukla/documents/AllSubjects/SOCG
mkdir /Users/charvieshukla/documents/AllSubjects/SOCE
mkdir /Users/charvieshukla/documents/AllSubjects/SOCI
mkdir /Users/charvieshukla/documents/AllSubjects/SE
mkdir /Users/charvieshukla/documents/AllSubjects/SURG
mkdir /Users/charvieshukla/documents/AllSubjects/SYN
mkdir /Users/charvieshukla/documents/AllSubjects/TDAC
mkdir /Users/charvieshukla/documents/AllSubjects/TDDE
mkdir /Users/charvieshukla/documents/AllSubjects/TDDR
mkdir /Users/charvieshukla/documents/AllSubjects/TDGE
mkdir /Users/charvieshukla/documents/AllSubjects/TDGR
mkdir /Users/charvieshukla/documents/AllSubjects/TDHT
mkdir /Users/charvieshukla/documents/AllSubjects/TDPW
mkdir /Users/charvieshukla/documents/AllSubjects/TDPR
mkdir /Users/charvieshukla/documents/AllSubjects/TMC
mkdir /Users/charvieshukla/documents/AllSubjects/USP
mkdir /Users/charvieshukla/documents/AllSubjects/UROL
mkdir /Users/charvieshukla/documents/AllSubjects/VIS
mkdir /Users/charvieshukla/documents/AllSubjects/WARR
mkdir /Users/charvieshukla/documents/AllSubjects/WCWP
mkdir /Users/charvieshukla/documents/AllSubjects/WES
